### ISSUE TITLE
node_modules

### ISSUE THREAD

**Issue by efiku** [korneliakobiela/VampireCSG#1]
Hejka!
Katalog **node_modules** powinien być wrzucony do .gitingore :) - o lie się nie mylę.

**Comment by korneliakobiela** [comment]
Załatwione

**Comment by efiku** [comment]
Proszę bardzo, pisałaś by wejść i zobaczyć co to, no to ..  :smile: 
Nie zapomnij wrzucić do .gitignore, bo na razie nie masz go w projekcie :)

**Comment by korneliakobiela** [comment]
Wiesz, zawsze to jakaś szansa na review, wskazówki, czy pomoc. Po prostu zdaję sobie sprawę, jak wiele jeszcze przede mną nauki i pracy, a wystawianie swoich wypocin na widok publiczny, to najszybsza droga do osiągnięcia celu. Dziękuję za poświęcony czas.
